const data = {
  products: [
    {
      _id: '1',
      type: 'paid',
      url: 'https://www.udemy.com/',
      name: 'Udemy',
      slug: 'udemy',
      category: 'Education',
      image: '/images/1.png',
      price: 120,
      countInStock: 1,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        'Udemy is an online learning platform that offers a wide range of courses taught by expert instructors. With a focus on practical skills, Udemy provides accessible and affordable education in various fields, from programming and web development to photography and business management.',
    },
    {
      _id: '2',
      type: 'free',
      url: 'https://www.coursera.org/',
      name: 'Coursera',
      slug: 'coursera',
      category: 'Education',
      image: '/images/2.png',
      price: 25,
      countInStock: 1,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        'Coursera is a leading platform for online education, offering courses, specializations, and even degree programs from top universities and institutions worldwide. With a diverse catalog covering subjects like data science, humanities, and engineering, Coursera provides flexible learning options for individuals seeking to enhance their knowledge and skills.',
    },
    {
      _id: '3',
      type: 'free',
      url: 'https://www.edx.org/',
      name: 'edX',
      slug: 'edx',
      category: 'Education',
      image: '/images/3.jpg',
      price: 250,
      countInStock: 1,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description:
        'edX is a trusted platform founded by Harvard University and MIT, providing high-quality online courses from universities, institutions, and organizations around the globe. Offering both individual courses and micro-credential programs, edX focuses on delivering rigorous academic content in subjects such as computer science, engineering, and business.',
    },
    {
      _id: '4',
      type: 'free',
      url: 'https://www.codecademy.com/',
      name: 'Codeacademy',
      slug: 'codeacademy',
      category: 'Programming',
      image: '/images/4.png',
      price: 65,
      countInStock: 1,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description:
        'Codecademy is an interactive platform designed to teach coding skills in a user-friendly and engaging manner. With hands-on projects and guided tutorials, Codecademy caters to beginners and intermediate learners interested in programming languages like Python, JavaScript, HTML, and more.',
    },

    {
      _id: '5',
      type: 'free',
      url: 'https://www.theodinproject.com/',
      name: 'The Odin Project',
      slug: 'the-odin-project',
      category: 'Web Development',
      image: '/images/5.png',
      price: 65,
      countInStock: 1,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description:
        'The Odin Project is a free and open-source curriculum designed to help individuals learn web development skills from scratch. Offering a comprehensive path covering HTML, CSS, JavaScript, and various frameworks, The Odin Project emphasizes practical projects and community support to facilitate learning.',
    },
    {
      _id: '6',
      type: 'free',
      url: 'https://www.freecodecamp.org/',
      name: 'FreeCodeCamp',
      slug: 'freecodecamp',
      category: 'Programming',
      image: '/images/6.png',
      price: 65,
      countInStock: 1,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description:
        'freeCodeCamp is a non-profit organization offering self-paced online coding courses and projects for individuals interested in web development and programming. Through its interactive platform, freeCodeCamp provides a structured curriculum covering topics like responsive web design, algorithms, and data visualization.',
    },
    {
      _id: '7',
      type: 'free',
      url: 'https://www.udacity.com/',
      name: 'Udacity',
      slug: 'udacity',
      category: 'Education',
      image: '/images/7.png',
      price: 65,
      countInStock: 1,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description:
        'Udacity offers industry-focused online courses and nanodegree programs designed in collaboration with leading companies. Specializing in tech-related fields such as artificial intelligence, autonomous systems, and data science, Udacity aims to equip learners with in-demand skills for the workforce.',
    },
    {
      _id: '8',
      type: 'paid',
      url: 'https://frontendmasters.com/',
      name: 'Frontend Masters',
      slug: 'frontendmasters',
      category: 'Web Development',
      image: '/images/8.png',
      price: 65,
      countInStock: 1,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description:
        'Frontend Masters is a platform providing in-depth courses and workshops for frontend developers looking to advance their skills. With a focus on cutting-edge technologies and best practices in frontend development, Frontend Masters offers expert-led training in areas like JavaScript, CSS, and frameworks like React and Angular.',
    },
  ],
};
export default data;
